name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo chmod +x magiskboot
          sudo chmod +x patch.sh
          sudo apt update
          sudo apt-get install -y lz4 tar openssl

      - name: Run custom script
        run: |
          sudo ./patch.sh

      # Subir el archivo patched-recovery.tar.md5 como artefacto
      - name: Upload patched-recovery.tar.md5 as artifact
        uses: actions/upload-artifact@v3
        with:
          name: patched-recovery
          path: patched-recovery.tar.md5
