name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y lz4 tar openssl
          sudo chmod +x magiskboot

      - name: Execute custom script
        run: |
          bash patch.sh
          
      - name: Upload patched-recovery.tar.md5 as artifact
        uses: actions/upload-artifact@v3
        with:
          name: patched-recovery
          path: patched-recovery.tar.md5
