#!/bin/bash

name: CI

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y lz4 tar openssl

      - name: Execute script
        run: |
          chmod +x magiskboot
          bash patch.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: patched-recovery.tar.md5
          name: Patched Recovery
          tag_name: ${{ github.run_id }}
